# Generated by Django 2.2 on 2019-05-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzers', '0002_analyzers_course'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
