# Generated by Django 2.1.5 on 2019-02-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KCsQuestionsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kcs.KCs')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='KCsStudentsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kcs.KCs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Students')),
            ],
        ),
    ]
