# Generated by Django 2.1.5 on 2019-02-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsStudentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'solved'), (2, 'studied/seen')], default=2)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Students')),
            ],
        ),
    ]
