# Generated by Django 2.1.5 on 2019-05-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('courses', '0002_coursesusermap_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.Category'),
        ),
        migrations.AddField(
            model_name='questionattempts',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='kcsusermap',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.KCs'),
        ),
        migrations.AddField(
            model_name='kcsusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kcsquestionsmap',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.KCs'),
        ),
        migrations.AddField(
            model_name='kcsquestionsmap',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='coursesquestionsmap',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='coursesquestionsmap',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='courseskcsmap',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='courseskcsmap',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.KCs'),
        ),
        migrations.AddField(
            model_name='categoryusermap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Category'),
        ),
        migrations.AddField(
            model_name='categoryusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
    ]
