# Generated by Django 2.2 on 2019-05-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
        ('courses', '0002_coursesusermap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='questionscategorycoursemap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Category'),
        ),
        migrations.AddField(
            model_name='questionscategorycoursemap',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='questionscategorycoursemap',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='questionattempts',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='kcsusermap',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.KCs'),
        ),
        migrations.AddField(
            model_name='kcsusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='kcsquestionsmap',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.KCs'),
        ),
        migrations.AddField(
            model_name='kcsquestionsmap',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='courseskcsmap',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='courseskcsmap',
            name='kc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.KCs'),
        ),
        migrations.AddField(
            model_name='categoryusermap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Category'),
        ),
        migrations.AddField(
            model_name='categoryusermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AddField(
            model_name='categorycoursemap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Category'),
        ),
        migrations.AddField(
            model_name='categorycoursemap',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
    ]
