# Generated by Django 2.1.5 on 2019-02-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190208_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsstudentsmap',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionsstudentsmap',
            old_name='students',
            new_name='student',
        ),
    ]
