# Generated by Django 2.2 on 2019-05-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesusermap_user'),
        ('questions', '0002_auto_20190514_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsusermap',
            name='course',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
            preserve_default=False,
        ),
    ]
