# Generated by Django 2.1.5 on 2019-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190511_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcs',
            name='importance',
            field=models.IntegerField(null=True),
        ),
    ]
