# Generated by Django 2.1.5 on 2019-05-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190507_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsCategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.AddField(
            model_name='questionscategorymap',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Questions'),
        ),
    ]
