# Generated by Django 2.1.5 on 2019-05-08 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesusermap_user'),
        ('questions', '0003_auto_20190508_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCourseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
        migrations.AddField(
            model_name='categorycoursemap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Category'),
        ),
        migrations.AddField(
            model_name='categorycoursemap',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Courses'),
        ),
    ]
