# Generated by Django 2.2 on 2019-05-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questionsusermap_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryusermap',
            name='status',
            field=models.IntegerField(choices=[(0, 'locked'), (1, 'unlocked'), (2, 'familiar'), (3, 'unfamiliar'), (4, 'edge')], default=0),
        ),
    ]
