# Generated by Django 2.1.5 on 2019-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190209_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsstudentsmap',
            name='status',
            field=models.IntegerField(choices=[(1, 'studied'), (2, 'correct'), (3, 'incorrect')], default=2),
        ),
    ]
