# Generated by Django 2.1.5 on 2019-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20190410_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsstudentsmap',
            name='status',
            field=models.IntegerField(choices=[(1, 'studied'), (2, 'correct'), (3, 'incorrect')], default=None),
        ),
    ]
